BandManager/Models/Show.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BandManager.Models
{
    public class Show
    {
        public virtual int ID { get; set; }

        public virtual Profile Profile { get; set; }

        [Required]
        [DisplayName("Venue or Show Name")]
        public virtual string VenueName { get; set; }

        [DisplayName("Venue Website")]
        public virtual string VenueWebsite { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Venue Address or Location")]
        public virtual string VenueLocation { get; set; }

        [DisplayName("Flier Photo")]
        public virtual string PhotoUrl { get; set; }

        [Required]
        [DisplayName("Date")]
        [DataType(DataType.Date)]
        public virtual DateTime Date { get; set; }

        [DataType(DataType.MultilineText)]
        public virtual string Description { get; set; }

        [DisplayName("Google Map Html")]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        public virtual string MapHtml { get; set; }

        public void update(Show show)
        {
            VenueName = show.VenueName;
            VenueWebsite = show.VenueWebsite;
            VenueLocation = show.VenueLocation;
            if (!string.IsNullOrEmpty(show.PhotoUrl))
            {
                PhotoUrl = show.PhotoUrl;
            }
            Description = show.Description;
            Date = show.Date;
            MapHtml = show.MapHtml;
        }
    }
}

BandManager/Areas/BandManager/Controllers/ShowsController.cs
using BandManager.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BandManager.Areas.BandManager.Controllers
{
    [Authorize]
    public class ShowsController : BaseProfileController
    {
        private void UploadPhoto(Show show, HttpPostedFileBase photo)
        {
            if (photo != null && photo.ContentLength > 0)
            {
                try
                {
                    show.PhotoUrl = Path.GetFileName(photo.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images/shows"), show.PhotoUrl);
                    photo.SaveAs(path);
                }
                catch (Exception ex)
                {
                    show.PhotoUrl = string.Empty;
                    ModelState.AddModelError("photo", string.Format("Error Uploading Image: {0}", ex.Message));
                }
            }
        }

        public ActionResult Index()
        {
            ViewBag.WebsiteUrl = profile.WebsiteUrl;
            var model = profile.Shows.OrderByDescending(s => s.Date);
            return View(model);
        }

        public ActionResult Create()
        {
            return View(new Show());
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(Show show, HttpPostedFileBase photo)
        {
            try
            {
                UploadPhoto(show, photo);
                profile.Shows.Add(show);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var show = profile.Shows.First(s => s.ID == id);
            return View(show);
        }

        [HttpPost]
        public ActionResult Edit(Show show, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                UploadPhoto(show, photo);
                profile.Shows.First(s => s.ID == show.ID).update(show);
                return RedirectToAction("Index");
            }

            return View(show);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                // needs a confirmation before deleting!
                var show = profile.Shows.First(s=> s.ID == id);
                profile.Shows.Remove(show);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

BandManager/Controllers/WebsiteController.cs
using BandManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BandManager.Controllers
{
    public class WebsiteController : Controller
    {
        Profile profile;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            profile = Session["currentProfile"] as Profile;
            base.OnActionExecuting(filterContext);
        }

        public ActionResult Index()
        {            
            return View(profile);
        }

        public ActionResult Shows()
        {
            ShowViewData model = new ShowViewData();
            model.UpcomingShows = new List<Show>(profile.Shows.Where(s => s.Date >= DateTime.Now).OrderBy(s => s.Date));
            model.PastShows = new List<Show>(profile.Shows.Where(s => s.Date < DateTime.Now).OrderByDescending(s => s.Date));
            return View(model);
        }

        public ActionResult ShowDetails(int id, string slug)
        {
            Show model = profile.Shows.First(s => s.ID == id);
            return View(model);
        }

        public ActionResult Media()
        {
            ViewBag.ReverbNationID = profile.ReverbNationID;
            var model = profile.Videos.OrderBy(v => v.Position);
            return View(model);
        }

        [HttpPost]
        public ActionResult Media(FormCollection collection)        
        {
            return RedirectToAction("Downloads");            
        }

        public ActionResult Band()
        {
            ViewBag.BandBio = profile.Bio;
            var model = profile.Members.OrderBy(m => m.Position);
            return View(model);
        }

        public ActionResult Contact()
        {
            ContactViewData model = new ContactViewData();
            model.profile = profile;
            model.Links = new List<Link>(profile.Links.OrderBy(l => l.Position));
            return View(model);
        }

        public ActionResult Downloads()
        {
            return View();
        }
    }

    public class ShowViewData
    {
        public List<Show> UpcomingShows { get; set; }
        public List<Show> PastShows { get; set; }
    }

    public class ContactViewData
    {
        public Profile profile { get; set; }
        public ICollection<Link> Links { get; set; }
    }
}

BandManager/Views/Website/Band.cshtml
@{
    ViewBag.Title = "Band";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="tilt-more">Meet the Band</h1>

<div class="feature-box">
<p>
    @ViewBag.BandBio
</p>
<div class="margin-top15">
    <strong>Members:
        @foreach (var item in Model)
        {
            <a href="#@item.Name.Replace(' ', '-')">@item.Name</a>
        }
    </strong>
</div>
</div>

<ul class="band">
    @foreach (var item in Model)
    {
        <li class="alternate">
          <div class="float1 half-width">
              @if (!string.IsNullOrEmpty(@item.PhotoUrl))
              {
                <img src="@Url.Content(string.Format("~/content/images/photos/{0}", @item.PhotoUrl))" />
              }
          </div>
          <div id="@item.Name.Replace(' ', '-')" class="float2 half-width block">
            <h5>@item.Name - @item.Instruments</h5>
            <p>@item.Bio</p>
            @if (!string.IsNullOrEmpty(@item.Gear))
            {
                <h6>@item.Name.Split(' ')[0]'s Gear</h6>
                <p>@item.Gear</p>
            }
          </div>
          <div class="clear"></div>
        </li>
    }
</ul>

BandManager/Views/Website/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="tilt-left">Contact Us</h1>

      <div class="feature-box">
        <h5>You can find us online at:</h5>
        <ul>
          @foreach (var item in Model.Links)
          {
              <li><a href="@item.Url">@item.Name</a></li>
          }
        </ul>
      </div>

      <form id="sendmail" action="sendmail.php" class="contact block">
        <h5>Or send us a message:</h5>
        <div>
          <label>Name</label>
          <input id="name" type="text" />
        </div>
        <div>
          <label>Email</label>
          <input id="email" type="text" />
        </div>
        <div>
          <label>Phone</label>
          <input id="phone" type="text" />
        </div>
        <div>
          <label>Reason for Contacting Us</label>
          <select id="subject">
            <option>General Inquiry</option>
            <option>Purchase tickets to an upcoming show</option>
            <option>I'd like to book Rando Tribe</option>
          </select>
        </div>
        <div>
          <label>Message</label>
          <textarea id="message"></textarea>
        </div>
        <div>
          <input id="btnsend" type="button" value="Send Message" />
          <span class="error"></span>
        </div>
      </form>

BandManager/Views/Website/Downloads.cshtml
@{
    ViewBag.Title = "Downloads";
}

<h1>Downloads</h1>

<div class="block center">
    <h3>Right click on any of the links below and click "Save As..." to download</h3>    
    <ul>
        <li><a href="http://www.randotribe.com/Full_DL/RandoTribe_Full_CD.zip">Full CD - All Songs ZIPPED</a></li>
        <li><a href="http://www.randotribe.com/Full_DL/Foxrock.mp3">Foxrock</a></li>
        <li><a href="http://www.randotribe.com/Full_DL/Im_ur_daddy.mp3">I'm Ur Daddy</a></li>
        <li><a href="http://www.randotribe.com/Full_DL/Reality_2day.mp3">Reality 2day</a></li>
        <li><a href="http://www.randotribe.com/Full_DL/dejavooey.mp3">Dejavooey</a></li>
        <li><a href="http://www.randotribe.com/Full_DL/everythings_a_mess.mp3">Everything's A Mess</a></li>
        <li><a href="http://www.randotribe.com/Full_DL/If_i_was_a_god.mp3">If I Was A God</a></li>
    </ul>
</div>
<h2>Thanks for Supporting our Music!</h2>

BandManager/Views/Website/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div>
    <div class="slideshow left">
        <img src="@Url.Content("~/content/images/photos/slide1.jpg")" />
        <img src="@Url.Content("~/content/images/photos/slide4.jpg")" />
        <img src="@Url.Content("~/content/images/photos/slide5.jpg")" />
        <img src="@Url.Content("~/content/images/photos/slide3.jpg")" />
        <img src="@Url.Content("~/content/images/photos/slide2.jpg")" />
    </div>
    <div class="music-player right">
        <div class="widget_iframe" style="display:inline-block;width:100%;height:348px;margin:0;padding:0;border:0;">
            <iframe class="widget_iframe" src="@string.Format("http://www.reverbnation.com/widget_code/html_widget/artist_{0}?widget_id=50&posted_by=artist_{0}&pwc[design]=default&pwc[background_color]=%23333333&pwc[included_songs]=1&pwc[photo]=0&pwc[size]=fit", Model.ReverbNationID)" width="100%" height="100%" frameborder="0" scrolling="no"></iframe>
            <div class="footer_branding" style="margin-top:-5px;font-size:10px;font-family:Arial;"></div>
        </div>
    </div>
    <div class="clear"></div>
    </div>

    <div class="block">
    <p>
        @Model.Description
        @Html.ActionLink("Download Pig Latin, our entire CD", "Media", null, null, null, "download", null, null)
    </p>
</div>

<h2>Love is an action we can all take... We'll go first!</h2>

BandManager/Views/Website/Media.cshtml
@{
    ViewBag.Title = "Media";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="align-right tilt-left">Music</h1>    

    <div class="full-width music-player">
        <div class="widget_iframe" style="display:inline-block;width:100%;height:320px;margin:0;padding:0;border:0;">
            <iframe class="widget_iframe" src="@string.Format("http://www.reverbnation.com/widget_code/html_widget/artist_{0}?widget_id=50&posted_by=artist_{0}&pwc[design]=default&pwc[background_color]=%23333333&pwc[included_songs]=1&pwc[photo]=0%2C1&pwc[size]=fit", ViewBag.ReverbNationID)" width="100%" height="100%" frameborder="0" scrolling="no"></iframe>            
        </div>
    </div>

    <h1 class="margin-top15">Videos</h1>
    @foreach (var item in Model)
    {
        <h3 class="center">@item.Name</h3>
        <div class="video">            
            @Html.Raw(item.VideoHtml)
        </div>            
    }
    


      <div id="download" class="block">
        <h5>
          So you like what you hear? Join our mail list by submitting your email address below and you will have access to download Pig Latin, our most recent CD.
        </h5>
        @using (Html.BeginForm())
        {
          <div>
            <label>First Name <span >*</span></label>
            <input name="FirstName" type="text" id="FirstName" />
          </div>
          <div>
            <label>Last Name</label>
            <input name="LastName" type="text" id="LastName">
          </div>
          <div>
            <label>Email Address <span >*</span></label>
            <input name="Email" type="text" id="Email">
          </div>
          <div>
            <input type="submit" value="Submit">
          </div>
          <div>
            <p>* Required</p>
            <p>
              All information gathered will be used by Rando Tribe ONLY. We will not use this information for sending you advertising of any type. This information will only be used to send updates on the Rando Tribe. We will not sell or give your infomation to anyone.
            </p>
          </div>
        }
      </div>

BandManager/Views/Website/ShowDetails.cshtml
@model BandManager.Models.Show

@{
    ViewBag.Title = "Show Details";
}

@section MetaTags {
    <meta property="og:title" content="@string.Format("Rando Tribe - {0}", Model.VenueName)" />
    <meta property="og:description" content="@string.Format("Rando Tribe - {0}", Model.Description)" />
}

<div class="block">
    
    <div class="left half-width">
        <h5>@string.Format("{0} - {1}", Model.Date.ToShortDateString(), Model.VenueName)</h5>
        <p>@Html.DisplayFor(model => model.Description)</p>
        @if (!string.IsNullOrEmpty(Model.VenueWebsite))
        {    
            <p><a href="@Model.VenueWebsite">Visit @Model.VenueName Website</a></p>
        }
        <p>@Html.DisplayFor(model => model.VenueLocation)</p>
        <div>@Html.Raw(Model.MapHtml)</div>
        <p>
            @Html.ActionLink("View all shows", "Shows")
        </p>
    </div>
    <div class="right half-width">
        @if (!string.IsNullOrEmpty(Model.PhotoUrl))
        {              
            <img src="@Url.Content(string.Format("~/content/images/shows/{0}", Model.PhotoUrl))" />              
        }
        else
        {
            <img src="@Url.Content("~/content/images/shows/generic-flier.jpg")" />
        }
    </div>
    <div class="clear"></div>
</div>

BandManager/Views/Website/Shows.cshtml
@model BandManager.Controllers.ShowViewData
@{
    ViewBag.Title = "Shows";
}

<h1>Upcoming Shows</h1>

<ul class="shows">
    @foreach (var item in Model.UpcomingShows)
    {
        @Html.Partial("_Show", item)
    }
</ul>

<h1 class="margin-top15">Past Shows</h1>

<ul class="shows">
    @foreach (var item in Model.PastShows)
    {
        @Html.Partial("_Show", item)
    }
</ul>

BandManager/Views/Website/_Show.cshtml
@using System.Text.RegularExpressions;

<li class="block">
    <h5>@Html.ActionLink(string.Format("{0} - {1}", (string)Model.Date.ToShortDateString(), (string)Model.VenueName), "ShowDetails", new { id = Model.ID, slug = Regex.Replace(Model.VenueName, "[^\\w]", "-") })</h5>
    <div class="left half-width">
    <p>@Model.Description</p>
    <p>@Model.VenueLocation</p>
    @Html.Raw(Model.MapHtml)
    </div>
    <div class="right half-width">
        @if (string.IsNullOrEmpty(Model.PhotoUrl))
        {   
            <img src="@Url.Content("~/content/images/shows/generic-flier.jpg")" />
                  
        }
        else
        {
            <img src="@Url.Content(string.Format("~/content/images/shows/{0}", Model.PhotoUrl))" />                   
        }
    </div>
    <div class="clear"></div>
</li>